import { StyleSheet, Platform, Dimensions } from 'react-native';
import { useFonts } from 'expo-font';

const { height } = Dimensions.get('window');

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    padding: 20,
    alignItems: 'center',
    justifyContent: 'center',
    paddingTop: Platform.OS === 'ios' ? height * 0.12 : 60, // Notch clearance
    paddingBottom: Platform.OS === 'ios' ? 40 : 20,
  },
  scrollContainer: {
    flex: 1,
  },
  titulo: {
    fontSize: 34,
    fontFamily: 'Poppins',
    fontWeight: 'bold',
    color: '#00695c',
    marginBottom: 15,
    marginTop: 0,
    textShadowColor: 'rgba(0, 0, 0, 0.2)',
    textShadowOffset: { width: 3, height: 3 },
    textShadowRadius: 4,
    textAlign: 'center',
  },
  imagem: {
    width: '70%',
    height: 250,
    resizeMode: 'contain',
    marginVertical: 20,
    borderRadius: 15,
  },
  metaContainer: {
    backgroundColor: '#fff',
    borderRadius: 12,
    padding: 10,
    marginBottom: 15,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.2,
    shadowRadius: 3,
    elevation: 3,
    borderLeftWidth: 4,
    borderLeftColor: '#00695c',
    fontFamily: 'Poppins',
  },
  metaText: {
    fontSize: 20,
    color: '#00695c',
    fontWeight: 'bold',
    textAlign: 'center',
    fontFamily: 'Poppins',
    // fontFamily: 'Poppins-SemiBold', // Add after font setup
  },
  cardContainer: {
    backgroundColor: '#fff',
    borderRadius: 18,
    padding: 20,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 5,
    elevation: 5,
    width: '92%',
    alignItems: 'center',
    marginBottom: 15,
  },
  inputContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#fff',
    borderRadius: 12,
    padding: 12,
    marginVertical: 12,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 5,
    elevation: 5,
    width: '85%',
    borderWidth: 1,
    borderColor: '#ddd',
  },
  input: {
    flex: 1,
    height: 40,
    fontSize: 16,
    color: '#333',
    fontFamily: 'Poppins',
    // fontFamily: 'Poppins-Regular', // Add after font setup
  },
  picker: {
    flex: 1,
    height: 40,
    borderWidth: 0,
  },
  pickerContainer: {
    flex: 1,
    height: 40,
    zIndex: 1000,
  },
  dropDownContainer: {
    backgroundColor: '#fff',
    borderColor: '#ddd',
    borderRadius: 12,
    zIndex: 1000,
  },
  resultado: {
    marginTop: 15,
    fontFamily: 'Poppins',
    fontSize: 18,
    color: '#00695c',
    fontWeight: 'bold',
    textAlign: 'center',
    // fontFamily: 'Poppins-SemiBold', // Add after font setup
  },
  reminderContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: '#fff',
    borderRadius: 12,
    padding: 12,
    marginVertical: 10,
    width: '85%',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.2,
    shadowRadius: 3,
    elevation: 3,
    borderLeftWidth: 4,
    borderLeftColor: '#00695c',
  },
  reminderText: {
    fontSize: 18,
    color: '#00695c',
    fontWeight: 'bold',
    fontFamily: 'Poppins',
  },
  registroContainer: {
    width: '92%',
    padding: 15,
    marginTop: 20,
    borderRadius: 15,
    backgroundColor: 'rgba(245, 245, 245, 0.9)',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.15,
    shadowRadius: 4,
    elevation: 4,
    borderTopWidth: 3,
    borderTopColor: '#00695c',
    fontFamily: 'Poppins',
  },
  registroHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 10,
  },
  registroTitle: {
    fontSize: 24,
    color: '#00695c',
    fontWeight: 'bold',
    textAlign: 'center',
    marginLeft: 8,
    fontFamily: 'Poppins',
  },
  historicoItemContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: 12,
    backgroundColor: '#fff',
    borderRadius: 10,
    marginVertical: 8,
    width: '100%',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 3,
    elevation: 3,
    borderLeftWidth: 5,
    borderLeftColor: '#00aaff',
  },
  historicoItem: {
    fontSize: 16,
    color: '#333',
    textAlign: 'left',
    fontFamily: 'Poppins',
    // fontFamily: 'Poppins-Regular', // Add after font setup
  },
  icon: {
    marginRight: 10,
  },
});