import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    padding: 20,
    alignItems: 'center',
    justifyContent: 'center',
  },
  scrollView: {
    width: '100%',
  },
  titulo: {
    fontSize: 32,
    fontWeight: 'bold',
    color: '#00695c',
    marginBottom: 25,
    fontFamily: 'Poppins',
    marginTop: 40,
    textShadowColor: 'rgba(0, 0, 0, 0.2)',
    textShadowOffset: { width: 1, height: 1 },
    textShadowRadius: 2,
    textAlign: 'center',
    backgroundColor: 'rgba(224, 247, 250, 0.3)',
    paddingVertical: 10,
    borderRadius: 15,
  },
  chartContainer: {
    marginVertical: 25,
    borderRadius: 16,
    overflow: 'hidden',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.25,
    shadowRadius: 5,
    elevation: 7,
  },
  chart: {
    borderRadius: 16,
  },
  mensagem: {
    fontSize: 18,
    color: '#00695c',
    fontWeight: 'bold',
    textAlign: 'center',
    marginVertical: 15,
    padding: 10,
    backgroundColor: 'rgba(0, 105, 92, 0.1)',
    borderRadius: 10,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 3,
    fontFamily: 'Poppins',
  },
  label: {
    fontSize: 22,
    marginBottom: 10,
    fontWeight: 'bold',
    marginTop: 20,
    color: '#00695c',
    textAlign: 'center',
    textShadowColor: 'rgba(0, 0, 0, 0.1)',
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 2,
    fontFamily: 'Poppins',
  },
  historicoItem: {
    fontSize: 16,
    color: '#333',
    marginVertical: 5,
    textAlign: 'left',
    flex: 1,
    fontFamily: 'Poppins',
  },
  historicoItemContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 15,
    backgroundColor: '#f5f5f5',
    borderRadius: 12,
    marginVertical: 8,
    width: '85%',
    alignSelf: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.15,
    shadowRadius: 4,
    elevation: 4,
  },
  icon: {
    marginRight: 15,
  },
});