import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    padding: 20,
    alignItems: 'center',
  },
  scrollView: {
    width: '100%',
  },
  deleteButton: {
  marginLeft: 10,
},
  titulo: {
    fontSize: 34,
    fontFamily: 'Poppins',
    fontWeight: 'bold',
    color: '#00695c',
    marginBottom: 20,
    marginTop: 60,
    textShadowColor: 'rgba(0, 0, 0, 0.2)',
    textShadowOffset: { width: 3, height: 3 },
    textShadowRadius: 4,
    textAlign: 'center',
    backgroundColor: 'transparent',
    paddingVertical: 10,
    borderRadius: 15,
  },
  section: {
    marginVertical: 10,
  },
  subtitulo: {
    fontSize: 22,
    color: '#333',
    textAlign: 'center',
    marginBottom: 10,
    fontWeight: 'bold',
    backgroundColor: 'rgba(0, 105, 92, 0.1)',
    padding: 5,
    borderRadius: 10,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 2,
    fontFamily: 'Poppins',
  },
  label: {
    fontSize: 22,
    marginTop: 30,
    marginBottom: 10,
    fontWeight: 'bold',
    color: '#00695c',
    textAlign: 'center',
    textShadowColor: 'rgba(0, 0, 0, 0.1)',
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 2,
    fontFamily: 'Poppins',
  },
  historicoItem: {
    fontSize: 16,
    color: '#333',
    marginVertical: 5,
    textAlign: 'left',
    flex: 1,
    fontFamily: 'Poppins',
  },
  historicoItemContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 12,
    backgroundColor: '#f5f5f5',
    borderRadius: 12,
    marginVertical: 6,
    width: '80%',
    alignSelf: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.15,
    shadowRadius: 4,
    elevation: 4,
    fontFamily: 'Poppins',
  },
  icon: {
    marginRight: 12,
  },
  chartContainer: {
    marginVertical: 20,
    borderRadius: 16,
    overflow: 'hidden',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.25,
    shadowRadius: 5,
    elevation: 7,
  },
  chart: {
    borderRadius: 16,
  },
});